# Generated by Django 3.0

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Initial migration for the lettings app.

    Creates the Address and Letting models with proper table names
    for backward compatibility with existing data.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999)],
                        help_text="Street number (1-9999)",
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=64, help_text="Street name"),
                ),
                (
                    "city",
                    models.CharField(max_length=64, help_text="City name"),
                ),
                (
                    "state",
                    models.CharField(
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        help_text="State abbreviation (exactly 2 characters)",
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)],
                        help_text="Postal/ZIP code (1-99999)",
                    ),
                ),
                (
                    "country_iso_code",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        help_text="ISO country code (exactly 3 characters)",
                    ),
                ),
            ],
            options={
                "db_table": "lettings_address",
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Letting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        help_text="Descriptive title for the property letting",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lettings.Address",
                        help_text="Associated address for this letting",
                    ),
                ),
            ],
            options={
                "db_table": "lettings_letting",
                "verbose_name": "Letting",
                "verbose_name_plural": "Lettings",
                "ordering": ["title"],
            },
        ),
    ]
